# Generated by Django 3.1.3 on 2020-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomper', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
