# Generated by Django 3.1.3 on 2021-01-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomper', '0003_gallery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='members',
        ),
    ]
