# Generated by Django 3.1.3 on 2021-01-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomper', '0004_remove_customer_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='pic_type',
        ),
    ]
